Update README.md
Fixing issue in the `slice` helper. Which were causing "Uncaught TypeError: object is not a function" error, due to incorrect use of the `block` object.